### ISSUE TITLE
翻訳を依頼する際に文言について

### ISSUE THREAD

**Issue by operando** [konifar/droidkaigi-session#48]
翻訳を依頼する場合に、ぞれぞれの文言がアプリのどこで使われているかによってニュアンスとか雰囲気ってちょっと変わってくるかなーと思うんですが、そこらへんって何か工夫とかってあるんですかね？
「翻訳お願いします、ドーン」というのと、「この文言はアプリのこの部分に使っていてこーゆーことを伝えたい」みたいなところまで教えてあげないと、アプリに実際にはめた際に「なんかこれ違う気がする？」とかあるのかなーとか思ったり。

**Comment by konifar** [comment]
すごくいい質問ですな！！！
ただ、眠みがひどいので明日返しますです

**Comment by konifar** [comment]
明日きっちり！

**Comment by operando** [comment]
ありがとうございます :+1: ！

**Comment by zaki50** [comment]
konifarさんの裏セッションでしたが、Sienaさんのセッションで note="..." で文字列のコンテキストを伝えるという話がありました。

```
<string name="campaign_ended_label"
             note="example: Ended on January 21, 2014">
 Ended on %s
</string>

```

https://www.slideshare.net/mobile/SienaAguayo/fearless-internationalization-and-localization-across-the-nations の23枚目あたりです

**Comment by konifar** [comment]
@operando 
変な話、翻訳のニュアンスについては弊社もまだ改善の余地はいっぱいあります。

そんな中で工夫してる点をいくつかあげます。

# いま工夫していること
1. GENGOの辞書機能を利用する
   GENGOには、辞書という機能があります。辞書とは、例えば 「Taptrip = Taptrip」のようにある単語はこのように訳してくださいという対応表です。日本語でも「友だち」と訳したほうがいいのか「友人」と訳したほうがいいのかは今までのアプリ内の単語によります。そのため、すでに出てきた機能の単語は辞書に登録するようにしています。
2. GENGO依頼時にニュアンスを指定する
   GENGOでは、翻訳を依頼するときにニュアンスを指定することができます。Taptripの場合は「フレンドリー」を指定しているので、日本語で言えば「〜しましょう」より「〜しよう」のような感じの翻訳になるようにお願いしています。
3. アプリのURLを一緒に渡して依頼する
   これは翻訳者にもよりますが、アプリを実際に触って確認してから翻訳してくれる人もいます。こちらからお願いすることはないですが、翻訳依頼時のコメントにアプリのURLを入れています。
4. 翻訳依頼時のコメント
   「この文言はこのアプリのこの部分に使うよ」ということを細かく指定できればいいのですが、時間がかかりすぎるのでそこまでできていません。今やっているのは、アプリの中の文言なので文字の長さはなるべく短くしてね、というコメントをつけて依頼しています。

以下は、今後取り組んでいきたいことです。

# やりたいこと
1. strings.xml内のコメント
   @zaki50 さんの指摘にあるように、strings.xml内でnoteやdescriptionをつけるというのはよさそうです。ただ、外部サービスに依頼する場合にここに書いたdescriptionをつたえるのは何か工夫が必要なのでどうしようかなぁという考え中です。
2. アプリからユーザーがフィードバックできる機能
   アプリからユーザーが翻訳の修正依頼を送れる機能を作りたいです。昔韓国の正しい翻訳をメールでまとめて送ってきてくれたユーザーがいたんですが、だいぶ大変だっただろうなと思います。イメージとしては、特定のユーザーが文字を長押しして正しい翻訳テキストを簡単に送信できるライブラリとかいいかもなぁと思ったりしています。

**Comment by operando** [comment]
なるほどー、細かく回答していただきありがとうございます！
zakiさんからも補足ありがとうございます！

GENGOの辞書機能とかニュアンス指定できるのは最高ですね！
アプリ内で用語が統一できてないとかの問題もそれならなんとかなりそう。

> strings.xml内のコメント

確かにnote良さそう！でもやっぱり文字で伝えたりするのは精度の限界とかありますよね。。。
さらに知見あれば今後聞きたい！！

> アプリからユーザーがフィードバックできる機能

ふむふむ。確かに対応する言語が多くなるとこれは欲しいですね。
細かい文言の調整など外部サービスに依頼したり、社内で色々検討したりするとわりと時間もお金もかかりますからね。
APIドキュメントとか大規模になってくると、ユーザが翻訳に手伝ってコンテンツを充実させていくって流れはありますからね。モチベーションを保つ工夫も必要ですが。(MozillaがやってるMDNそんな感じ)
Taptripのようなサービスならむしろその機能はあるべきかもしれないので、今後に期待してます！

ではissueはCloseしますね！回答ありがとうございました！
トゥットゥルー♪
